announcement-interval: 60
announcements:
  1:
    - ' '
    - ' '
    - '<color:#5865F2><bold>Make sure to join our discord!'
    - ' '
    - "<white><click:open_url:'https://discord.gg/taQMwHdUQE'>discord.gg/taQMwHdUQE</click>"
    - ' '
    - ' '
  2:
    - ' '
    - ' '
    - '<color:#12c2e9><bold>Make sure to add the IP to your server list!'
    - ' '
    - '<white>bozokits.net'
    - ' '
    - ' '
  3:
    - ' '
    - ' '
    - '<green><bold>Make sure to visit our store!'
    - ' '
    - "<green><click:open_url:'https://store.bozokits.net'>store.bozokits.net</click>"
    - ' '
    - ' '
  4:
    - '<green><bold>You can claim a FREE reward every single day!'
    - '<gray>Type /daily to claim it!'
  5:
    - "<green><bold>You can get free coins just by AFK'ing!"
    - "<gray>Type /afk to go there!"
  6:
    - ' '
    - '<color:#5865F2><aqua><bold>WANT <dark_green><bold>HERO RANK</dark_green> FOR FREE?!'
    - '<color:#5865F2>Just link your mc account on our discord'
    - '<gray>Type /link and join the discord'
    - ' '
    - "<color:#5865F2><click:open_url:'https://discord.gg/taQMwHdUQE'>discord.gg/taQMwHdUQE</click>"
    - ' '
commands-on-death:
  - 'kit <random-1-50> <player>'
commands-on-kill:
  - 'kit bozocoin <player>'
commands-anvil-reset:
  - 'setblock -69 158 14 anvil[facing=west]'
  - 'setblock -72 158 10 anvil[facing=north]'
  - 'setblock -72 158 -10 anvil[facing=north]'
  - 'setblock -69 158 -14 anvil[facing=east]'
shout-command:
  - ' '
  - ' '
  - '<white>[<gradient:#12c2e9:#C471ED:#f64f59><bold>BOZO KITS</gradient>] <color:#12c2e9><bold><content>'
  - ' '
  - ' '
shoutsmall-command:
  - '<white>[<gradient:#12c2e9:#C471ED:#f64f59><bold>BOZO KITS</gradient>] <color:#12c2e9><bold><content>'
shoutsmalllol-command:
  - '<color:#12c2e9><red><content>'
rngtest-command:
  - ' '
  - ' '
  - '<white>[<gradient:#12c2e9:#C471ED:#f64f59><bold>BOZO KITS</gradient>]<color:#12c2e9><bold> <random-1-80>'
  - ' '
  - ' '
event-win:
  - ' '
  - ' '
  - '<white>[<gradient:#ff244c:#f5142d><bold>EVENT</bold></gradient><white>] <white><bold><player> <color:#ff244c><bold>WON
    THE EVENT AND WON<white><bold>:'
  - '<white><bold>32 <gold>Bozo Coins <white><bold>+ 1 <gradient:#4a00e:#8e2de2>ULTRA</gradient><color:#8e2de2><bold>Crate Key<white>!'
  - ' '
  - ' '
free-rank:
  - '<green>You claimed your free rank! <light_purple><bold>BUT:'
  - ' '
  - ' '
  - '<color:#12c2e9><bold>Make sure to add the IP to your server list!'
  - ' '
  - '<white>bozokits.net'
  - ' '
  - ' '
discordboughtlegendarycrate:
  - '> \💸 **<player>** bought a `Legendary Crate` :Legendary:'
discordbozocrate:
  - '> \🔑 **<player>** won `<arg1>` from `Bozo Crate` :Bozo:'
discordlegendarycrate:
  - '> \🔑 **<arg1>** won `<arg2>` from `Legendary Crate` :Legendary:'
lucky-dip:
  - '<green>CONGRATULATIONS!'
  - '<green>You were very lucky & won a free daily hero rank voucher! Check your inventory for it.'
event-join: '<white>[<gradient:#12c2e9:#C471ED:#f64f59><bold>BOZO KITS</gradient>]<color><bold> /event join'
text-commands:
  ip:
    - ' '
    - ' '
    - '<color:#12c2e9><bold>Make sure to add the IP to your server list!'
    - ' '
    - '<white>bozokits.net'
    - ' '
    - ' '
  discord:
    - ' '
    - ' '
    - '<color:#5865F2><bold>Make sure to join our discord!</bold>'
    - ' '
    - "<white><click:open_url:'https://discord.gg/taQMwHdUQE'>discord.gg/taQMwHdUQE</click>"
    - ' '
    - ' '
  store:
    - ' '
    - ' '
    - '<green><bold>Make sure to visit our store!'
    - ' '
    - "<green><click:open_url:'https://store.bozokits.net'>store.bozokits.net</click>"
    - ' '
    - ' '
  help:
    - ' '
    - ' '
    - '<gradient:#00d9ff:#92fbff><bold>Bozo Kits Help'
    - ' '
    - '<aqua>[?] <gradient:#ca00f7:#ff38e4>- Get a random kit on every death.'
    - '<aqua>[?] <gradient:#ca00f7:#ff38e4>- Get a bozo coin on every death.'
    - '<aqua>[?] <gradient:#ca00f7:#ff38e4>- You drop your head on every death.'
    - '<aqua>[?] <gradient:#ca00f7:#ff38e4>- Trade bozo coins for items at spawn.'
    - '<aqua>[?] <gradient:#ca00f7:#ff38e4>- You can die if you combat log.'
    - ' '
    - '/shop <gradient:#ca00f7:#ff38e4>- Withdraw and deposit bozo coins.'
    - '/deposit hand <gradient:#ca00f7:#ff38e4>- Quickly deposits bozo coins in your hand.'
    - '/coins <gradient:#ca00f7:#ff38e4>- View your deposited coins.'
    - '/pay (user) (amount) <gradient:#ca00f7:#ff38e4>- Give someone your coins.'
    - '/topcoins <gradient:#ca00f7:#ff38e4>- View top balance leaderboard.'
    - '/coinflip <gradient:#ca00f7:#ff38e4> Gamble your coins with others.'
    - '/pvpstats <gradient:#ca00f7:#ff38e4>- View your PVP stats.'
    - '/pvpstats <player> <gradient:#ca00f7:#ff38e4>- View someone''s PVP stats.'
    - '/shulker <gradient:#ca00f7:#ff38e4>- TP''s you to a random shulker room.'
    - '/afk <gradient:#ca00f7:#ff38e4>- Teleports you to the AFK pool.'
    - '<gold>/daily - Get a free reward every 24h.'
    - '<gold>/link - Get hero rank for free.'
    - '<gold>/serverip (/ip) - View the server IP.'
    - '<aqua>/store - Get a link to our store.'
    - ' '
    - '<gradient:#ca00f7:#ff38e4>Need further assistance?'
    - '<gradient:#ca00f7:#ff38e4>/discord'
    - ' '
    - ' '
  rules:
    - ' '
    - ' '
    - '<gradient:#ff244c:#f5142d><bold>Bozo Kits Rules'
    - ' '
    - '<color:#ff244c>There are many rules that you agree to by playing.'
    - '<color:#ff244c>Failure to follow the rules may end in a punishment.'
    - '<color:#ff244c>All rules can be found on the discord!'
    - '<color:#f5142d>discord'
    - ' '
    - ' '
  afkpoolleave:
    - ' '
    - ' '
    - '<red><bold>You will no longer receive rewards for AFK''ing!'
    - ' '
    - '<gray>(10 Bozo Coin every 30 minutes)'
    - ' '
    - ' '
  afkpooljoin:
    - ' '
    - ' '
    - '<green><bold>Make sure to visit our store!'
    - ' '
    - "<green><click:open_url:'https://store.bozokits.net'>store.bozokits.net</click>"
    - ' '
    - ' '
messages:
  join-title: '<gradient:#12c2e9:#C471ED:#f64f59><bold>BOZO KITS</gradient>'
  join-subtitle: '<gray>Welcome to our server!'
  levitation: '<green><bold>You have been <light_purple>levitated!'
  speed-and-jump: '<green>You have been given <aqua>Speed & Jump Boost!'
  extra-hearts: '<green>You have been given 4x <red><bold>Extra Hearts!'
  join-motd:
    - ' '
    - ' '
    - '      <gradient:#12c2e9:#C471ED:#f64f59><bold>BOZO KITS</gradient>'
    - '         <color:#f64f59>Welcome <player>!'
    - ' '
    - '         <gray>Type /help for help'
    - ' '
    - ' '
  first-join-message: '<gray>[<green>✔<gray>] <player> <gold>#<unique-players>'
  join-message: '<gray>[<green>✔<gray>] <player>'
  leave-message: '<gray>[<red>❌<gray>] <player>'
  no-permission: '<red>You do not have enough permissions for this command!'
  afk-pool: '<green>Jump into the AFK pool to start earning!'
  shulker-room: '<green>You have been teleported to a random shulker room!'
  keyall-start: '<gray>You have started a <green>daily crate keyall<gray>. <green>[7min] (~14 min)'
  plugins: '<white>Plugins (5): <green>Mate<white>, <green>You<white>, <green>An<white>, <green>Actual<white>, <green>Bozo'
  kill-player:
    - '<green>You received a bozo coin for killing <white><victim>'
    - '<gray>Put it in the bank to keep it safe <white>/shop'
  daily-reward-shout: '<yellow>☀ <light_purple><player> <green><bold>claimed their daily reward!</bold> <gray>Type /daily'
  daily-reward: '<white>[<gradient:#12c2e9:#C471ED:#f64f59><bold>BOZO KITS</gradient>] <green><bold>You have claimed your daily reward!'
  report:
    - ' '
    - '<color:#5865F2><bold>Your report has been sent to the staff:'
    - '<white>"<content>"'
    - ' '
    - '<color:#5865F2>You can submit another report in <green>15min.'
    - ' '
  on-cooldown: '<gray>You can''t do this until another <green><cooldown></green>.'
  eventdied: '<red><bold>YOU DIED!</bold></red>'
  eventdiedsub: '<gray>Type /event leave to exit!'
  eventyoukilled: '<red><bold>YOU KILLED</bold></red>'
  eventyoukilledsub: '<dark_red>☠ <victim> ☠'
  eventwin: '<gold><bold>VICTORY!'
  eventwinsub: '<gray>Enjoy your prizes!'
  boosting: '\🔥 **<player>** used /booster 🔥🔥🔥🔥🔥'