name: BozoKitsUtils
version: '${project.version}'
main: net.bozokits.BozoKitsUtils
api-version: 1.19
commands:
  ip:
    description: Server ip message
  help:
    description: help command
    aliases:
      - helpme
  discord:
    description: discord invite
  store:
    description: server store
  rules:
    description: rules
    aliases:
      - serverrules
  newshout:
    description: shout command
    permission: bozokits.newshout
  newshoutsmall:
    description: small shout command
    permission: bozokits.newshoutsmall
  newshoutsmalllol:
    description: funny small shout command
    permission: bozokits.newshoutsmalllol
  potionshop:
    aliases:
      - potshop
  foodshop:
    description: food shop
  coinshop:
    description: coin shop
  boomshop:
    description: boom shop
  miscshop:
    description: misc shop
  specialshop:
    description: special shop
  bookshop:
    description: book shop
  xpshop:
    description: xp shop
  afkpool6969leave:
    description: afk pool leave
  afkpool6969join:
    description: afk pool join
  afk:
    description: afk warp command
  rngtest:
    description: rng test
    permission: bozokits.rngtest
  arena-reset:
    description: arena reset
    permission: poglords.resetarena
  daily:
    description: daily reward
  randomkit:
    description: gives a random kit
    permission: bozokits.randomkit
  nightvision:
    description: gives permanent night vision
  discordboughtlegendarycrate:
    description: legendary crate buy
  keyall:
    description: gives keys to everyone
    permission: poglords.keyall.daily
  discordlegendarycrate:
    description: legendary crate open
  discordbozocrate:
    description: bozo crate
  shulker:
    description: teleports to a random shulker room
  eventjoinwhite:
    description: event join message
    permission: poglords.eventjoinwhite
  eventjoinwhitechance:
    description: event join message
    permission: poglords.eventjoinwhitechance
  eventjoinred:
    description: event join message
    permission: poglords.eventjoinred
  eventjoinredchance:
    description: event join message
    permission: poglords.eventjoinredchance
  eventyoukilled:
    description: event title
    permission: bozokits.eventadmin
  eventdied:
    description: event title
    permission: bozokits.eventadmin
  eventwin:
    description: event title
    permission: bozokits.eventadmin
  eventwinner:
    description: event winner commands
    permission: bozokits.eventadmin
  freerank:
    description: gives free rank every 24h
  luckydip:
    description: lucky dip
    permission: bozokits.luckydip
  boosting:
    description: boosting reward
    permission: bozokits.boosting